apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: experiment-platform
resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml
  - ghcr-pull-secret.yaml
  - backend-sealed-secret.yaml
commonLabels:
  environment: production
  project: experiment-platform
images:
  - name: ghcr.io/pseudo-lab/experiment-platform-pseudolab-frontend
    newName: ghcr.io/pseudo-lab/experiment-platform-pseudolab-frontend
    newTag: cafb169b69c6bea67110d0e3e118cf7a84790dbe
  - name: ghcr.io/pseudo-lab/experiment-platform-pseudolab-backend
    newName: ghcr.io/pseudo-lab/experiment-platform-pseudolab-backend
    newTag: cafb169b69c6bea67110d0e3e118cf7a84790dbe
