apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: experiment-platform
resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml
  - ghcr-pull-secret.yaml
  - backend-sealed-secret.yaml
commonLabels:
  environment: production
  project: experiment-platform
images:
  - name: ghcr.io/pseudo-lab/experiment-platform-pseudolab-frontend
    newName: ghcr.io/pseudo-lab/experiment-platform-pseudolab-frontend
    newTag: e063dced290265980c21f7741e11c41ea691273e
  - name: ghcr.io/pseudo-lab/experiment-platform-pseudolab-backend
    newName: ghcr.io/pseudo-lab/experiment-platform-pseudolab-backend
    newTag: e063dced290265980c21f7741e11c41ea691273e
