apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: experiment-platform
resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml
  - ghcr-pull-secret.yaml
  - backend-sealed-secret.yaml
commonLabels:
  environment: production
  project: experiment-platform
images:
  - name: ghcr.io/pseudo-lab/experiment-platform-pseudolab-frontend
    newName: ghcr.io/pseudo-lab/experiment-platform-pseudolab-frontend
    newTag: ea50b8a047565a8e6df642821a879894c8893f30
  - name: ghcr.io/pseudo-lab/experiment-platform-pseudolab-backend
    newName: ghcr.io/pseudo-lab/experiment-platform-pseudolab-backend
    newTag: ea50b8a047565a8e6df642821a879894c8893f30
