---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-creds-experiment-platform
  namespace: experiment-platform
spec:
  encryptedData:
    .dockerconfigjson: AgAtXry1iHyOWCIcmQvASn4M1Y/UqG1GqvdQ3633wfJUyXaKNsPHs7vHfrdHTxgHD+X1lo2A0lzeRXutsHFVF0twkc8HRZfE1oApZ5OC925y1c26fVpO7qAli+jR0w1tNQWvUN5Yr9lBji5mJC0teBuJGQ5DYQKmMRuapofdS1nbsFtAnLQAlIb8QeYnGYArDmtP92rK9NzNSNjElIStr+/rYpNh93N88vgOEoNGgeAJuyCj9WbmBLq77utFtM05K+L5wI0+Xo3e4jGEC0iPbsGOEsQTPlrU42+jqRP81AfyFhhj95QO2RCuugPYtOX2KG4QOFEouOwRREbFBqWdBcynHnc3ISzXR111ZeLBLN6c7mrvwjsQ3XqT6Qr4CuUgJwjFEs4XDFX45AfMBCpJO5VLTwx6vUkxgA0Y6r/kKnrWTM5PaR2zbS070HMsZZQgsPVTwFDTzf0G0R6JQpbyhx5P9I00OzGCkcaCLFiuiHYQju9GU/aUyyP+9vs3d/3SlmfIo9fd6MQQWnGpEau1wladI+3KAFU5c6N07z8HNaMj0S2OFvvSe9K1sfkIll6YHxxx9YDHadGo2+NP/F7JBlz/fWkPKtxjrR0QLy5n/tlhlQvHS3JFPccHZPv7JwuCHb4z6m7kyoMiMSZm2jp4YFkHHUt+jdgI1rln6OUy2WVmdXIJqWt487mz4T+4GnT/uQvjE+KwcCzYMsqwjJCqVG+EpYQ4DrVLvrehvF9+FTHL8bYHvHUSSDtQObWexLsREBGW/5OO/Zlwrqrm+WO8OyJBI51gWv/rHxNQAZzcyka52YZAZ5WNR697pOwT1IlgvQb7ydV0m+6yhir70Qs/JtYI3w/gPLDzlP1vLx3CtLvHMgJhjP+yuoKUqdnSPFzNB6cgwTNrPs1h7rSPjOCnREgYcDsI42anYPYOBahFC3bgQ2she/RuvhE2bPRT58ss4LWJk/bVo1PglXbgpfBSEcEUF2E=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-creds-experiment-platform
      namespace: experiment-platform
    type: kubernetes.io/dockerconfigjson
