---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-creds-experiment-platform
  namespace: experiment-platform
spec:
  encryptedData:
    .dockerconfigjson: AgBGjJ+mrr8XraHLpv7cw98cpdsxLqKcF4iKmowdcb022SN/x8R0J/AtjFprZ/PlNKreTyxR+DCECdqyTH2oNUXDXeDL4a9kLFbXTv3FVnv4+i7GrOS4afI0bKjNmRGDPhfbE0NnoQ+M7uKcJCEJeFpC/RkJQGpVgyr45CjWq3MFEMuWvJzdN5glAZ+TOx/iNQBf1O0yTczyfCi3YCP22AviU7/81YTgj3+fYtzoCiV3VFuBWMiAQb23XB3vZYdXzaVBXFoFWN/t1evkKF5orue/oZ0VEUq30nvA9A/yP2MHrTsF78dS4goDLC+4QrSpmkI9L3lMCA4lBkNFblcoqRantz86xYOGouh+9Agg+ztbcSRgc/t6AsM4ydCtsRTQDHfCixM2nV0YX6xPodzdk8PjdBsM+EOfjiTqHXD91PgCWMtvHatrN/eB3l0ODVDWUqBR75CJ8v8GMCbLY2mw+vaEqsGQ3uq77yrLo7zIgpsDD0wXvvtYk0jPf2DyXQF5sf2Xrr9YC6aV5y0kEJnxlQI+pmZVHtlkMMFZs0LNoy2tqpWZJqH3pelW5z70F2klRVvkNdtNH4+njd/SbrXCRCqz09T1gIDKeSMtPNxujnKODIOS2rX9Rue9womqZXZ0kzkerNOGUp1wTNFTWWfzocYPxo2zCPKbZr5eFUkStUGQ0vhvzd7p/IQsGPWUVyMPyCnyyreCFvELbC6wjkQxD81gVYK+3bwIe/ac/EMzXqvoX4IeD6t5VjxW/OYVJou2Hi69Y76kQA96veicVjVGerZ2zRdznXAZDdkG25a/X2itU1MoB2EKlKwHnHdAp1ueY/QL0jwRUqQ7i4gfeQ+Iyz1NfIQZ/1vIl81DzRMS1Hex2oY/RoDNuBMuZzzou/bf/w+t7UBsD3dWmhk06O/k4QJzjOjArT445i9yFmWHsuyJUnfQbvVOrD13
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-creds-experiment-platform
      namespace: experiment-platform
    type: kubernetes.io/dockerconfigjson
