---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-creds-experiment-platform
  namespace: experiment-platform
spec:
  encryptedData:
    .dockerconfigjson: AgAgKGTVwwuYXX6NdNXUiV85w8c97lQImWaIWwgFSsail1dtqqCe8f2GjKP5KN7Qm0W5d2BgRnu6ls3nl3ZKeue6b0JjRktL+Rw+r1xb35tpM1b4UakJCWomyMKwcoqJvrQ+wXBOLDPboGk/J+Cvx69PwgGuclBNWN7UtqB4lfrprbjmESujYCfSBF8xVATueAV7EY8NSym5ClVBAem7/uuEVRvl0GxL8DgPfI9/kJT8pbIcvC5+oDEcJwNXvSMDl7OsS1hskYNzZ70vcKfNoxd3zAtPhxiGsc7WC8EROpD3e4nIkYoAqODURl3xqw590W9AiGUj6/TA3Y8qAWadG/SOaGh2zJ9n3ONd9p3WiaCwuUgfo3bbeTaOoEo6HeGZllT6QeNPc7GOlX+vqjPuIzXVq85Flt7QC2RscQoM4lG+DJLZlgUeipxui40cZYihy1yw1OL9izQJMYehDeDIc4XPMqclG9/IQIjlW0Uy3guu5CPvSwxvTVuZwh95LRoagzraWpG8yFYNJocEG9/f946oLjIeKpX/pYoYMyIOyBVcxkAewsRakt1FVgM0W3qaIcNsvlNMwfFwyhRzkdbYm7mVgAZzHC+TGuu7AAlsW4zDCSnOFagHNUNuulsTmyYokKeF2wzS4yEoszCMAgJT6qQxs1yJ6sWf3arrTLXL5moHNe7om4FiylIDgTHIIqtqcOROSLUTTM47aQpcmca7dOSTz0T/pSCKdrxr9ompaLvtq0GWZm06mxIXYmp7Uux5ArNWCPhsh1r1Oaa+ld95BA7NWD0QZl8JyhMF+x+1hxDJ3dOS96+md0BlB5DYGRAtZ4imNZfQz2s9XrK/6/qU65TvfBHrm7G/nKRTCefP3T+lg1sSl7PXJMe94jySTg0XevVGF+HSAVhKaKoj4Rjhrf9OT0nk46936W0MjOJ9epocRNjb
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-creds-experiment-platform
      namespace: experiment-platform
    type: kubernetes.io/dockerconfigjson
