apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: experiment-platform
resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml
commonLabels:
  environment: production
  project: experiment-platform
images:
  - name: ghcr.io/pseudo-lab/experiment-platform-frontend
    newName: ghcr.io/pseudo-lab/experiment-platform-frontend
    newTag: 3d5c7a0e51a217aa7a3ff1d8ea6555260bf8de0e
  - name: ghcr.io/pseudo-lab/experiment-platform-backend
    newName: ghcr.io/pseudo-lab/experiment-platform-backend
    newTag: 3d5c7a0e51a217aa7a3ff1d8ea6555260bf8de0e
