apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: experiment-platform
resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml
  - ghcr-pull-secret.yaml
commonLabels:
  environment: production
  project: experiment-platform
images:
  - name: ghcr.io/pseudo-lab/experiment-platform-frontend
    newName: ghcr.io/pseudo-lab/experiment-platform-frontend
    newTag: d9b058c9d7e68eb5c053a03200663f360b9dfc58
  - name: ghcr.io/pseudo-lab/experiment-platform-backend
    newName: ghcr.io/pseudo-lab/experiment-platform-backend
    newTag: d9b058c9d7e68eb5c053a03200663f360b9dfc58
