apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-experiment-platform

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml

commonLabels:
  environment: production
  project: experiment-platform

images:
  - name: ghcr.io/pseudo-lab/experiment-platform-frontend
    newName: ghcr.io/pseudo-lab/experiment-platform-frontend
    newTag: PLACEHOLDER
  - name: ghcr.io/pseudo-lab/experiment-platform-backend
    newName: ghcr.io/pseudo-lab/experiment-platform-backend
    newTag: PLACEHOLDER