apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Pseudo-Lab/DevFactory-Ops.git
    targetRevision: main
    path: services/homepage/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: apps-homepage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
