apiVersion: apps/v1
kind: Deployment
metadata:
  name: experiment-platform-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: experiment-platform
      component: backend
  template:
    metadata:
      labels:
        app: experiment-platform
        component: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/pseudo-lab/experiment-platform-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
