apiVersion: v1
kind: Service
metadata:
  name: hackathon-platform-api
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  selector:
    app: hackathon-platform
    component: api
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
