apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-platform-api
  annotations:
    secret.reloader.stakater.com/reload: hackathon-platform-api-secret
    configmap.reloader.stakater.com/reload: hackathon-platform-api-config
spec:
  revisionHistoryLimit: 5
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: hackathon-platform
      component: api
  template:
    metadata:
      labels:
        app: hackathon-platform
        component: api
    spec:
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: ghcr-creds-hackathon-platform
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: api
          image: ghcr.io/soohyunme/hackathon-platform-api
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: hackathon-platform-api-config
            - secretRef:
                name: hackathon-platform-api-secret
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
          startupProbe:
            httpGet:
              path: /api/health/live
              port: http
            periodSeconds: 2
            timeoutSeconds: 1
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /api/health/live
              port: http
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health/ready
              port: http
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
