apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-platform-web
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  revisionHistoryLimit: 5
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: hackathon-platform
      component: web
  template:
    metadata:
      labels:
        app: hackathon-platform
        component: web
    spec:
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: ghcr-creds-hackathon-platform
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: web
          image: ghcr.io/soohyunme/hackathon-platform-web
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
