apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-redirect

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: cert-redirect-nginx
    files:
      - nginx.conf
