apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
    # Helm Chart: cert-manager controller
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.14.4
      helm:
        valueFiles:
          - $values/infrastructure/base/cert-manager/values.yaml
    # Values source for $values interpolation
    - repoURL: https://github.com/Pseudo-Lab/DevFactory-Ops.git
      targetRevision: main
      ref: values
    # Git Manifest: ClusterIssuer configuration
    - repoURL: https://github.com/Pseudo-Lab/DevFactory-Ops.git
      targetRevision: main
      path: infrastructure/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
