apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-common
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Pseudo-Lab/DevFactory-Ops.git
    targetRevision: main
    path: infrastructure/base/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
