apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://victoriametrics.github.io/helm-charts/
      chart: victoria-metrics-k8s-stack
      targetRevision: 0.70.0
      helm:
        valueFiles:
          - $values/infrastructure/base/monitoring/victoria-metrics/values.yaml
    - repoURL: https://github.com/Pseudo-Lab/DevFactory-Ops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: victoria-metrics-victoria-metrics-operator-validation
      namespace: monitoring
      jsonPointers:
        - /data/ca.crt
        - /data/tls.crt
        - /data/tls.key
    - group: "admissionregistration.k8s.io"
      kind: ValidatingWebhookConfiguration
      name: victoria-metrics-victoria-metrics-operator-admission
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
