apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bingo-backend
spec:
  template:
    spec:
      containers:
        - name: event-bingo-backend
          env:
            - name: DB_POOL_SIZE
              value: "3"
            - name: DB_MAX_OVERFLOW
              value: "1"
            - name: DB_POOL_TIMEOUT_SECONDS
              value: "5"
