apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: event-bingo-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: bingo.pseudolab-devfactory.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: event-bingo-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: event-bingo-frontend
                port:
                  number: 80
