apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: event-bingo

resources:
- ../../base
- namespace.yaml
- ingress.yaml
- ghcr-pull-secret.yaml
- sealed-secret.yaml

commonLabels:
  environment: production
  project: event-bingo

images:
- name: ghcr.io/pseudo-lab/event-bingo-backend
  newName: ghcr.io/pseudo-lab/event-bingo-backend
  newTag: sha-41c1287
- name: ghcr.io/pseudo-lab/event-bingo-frontend
  newName: ghcr.io/pseudo-lab/event-bingo-frontend
  newTag: sha-41c1287
