apiVersion: v1
kind: ConfigMap
metadata:
  name: hackathon-platform-api-config
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
data:
  APP_ENV: production
  PUBLIC_APP_URL: https://hackathon.pseudolab-devfactory.com
  LOG_LEVEL: INFO
