---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-creds-hackathon-platform
  namespace: hackathon-platform
spec:
  encryptedData:
    .dockerconfigjson: AgCCJUrhdySvrkd6VdTWSDwoE5SaUp1CyvgiJ53T6MX6MOFi+Q4mXlOVyF1jKVx940OlMA3DMRkzjr53a2bZb2uDXe5aFJa/JxSRYYIMQrfUdZAB1zqP+G9iDImgpjySEIZrN8NXnYq5rMfs3VeXz0PzbWwuAr+0DSVrB0UkkdhTZ6uA14ZEL4XQz9FfUqrMO2cGhKTWTd9x5qaNG3XZLVRmqaqBswbcT4huNIz+u7xTKgUcZvrG5nqCroxzQQ2pGYNnc9hniiCeK51eBFq2i6OuvlaA0TsYetJKP/hLaH41rzzjcKADCO9kHUmGk3GtVR6GO1DJtOgTQRldfW3XzyuiofMqMmbPpTP6PZ1xbNZcpB3RK4mmqK2MmVxaV4+ApizVM7KqBkrh+lsivOmebac23aMi2z7fkcOjOWV4uKCuDu5qDAh1SnC7H0/KiAx+JGNhDX4xlQ39hNGupHUNf7B5BrULMPjM1D7yLA3dfzsC4piFfcSEQIvQaiTyZlkx0mgTqSylLctI5fR3phm1f34Uop/6+4KskotZyraCVX2Yg0gUqBC3a8rkog7xV4gITtNBgTXhfOV2RSxdxhS36CB1GN38MNaYbv2KPjpEB+dMuxlkOo9a63Rjv9dL7ktwOliUxxNBRhhTHwkme6+M03RPZHecP2Hw4Tl/KvliAMmIcrARF9fTBZxQ5dkWS7IfzkoVi04bkbzBvIRFFXfMuNgt9iGroKBNkZmSW8M1TQPqYKolAifp8/lj96ire61pfv1Exurg3bxl3NJPjIwtocZj9yJhq/LtEjYq2w40DBfSS9E5co6cMRXqbfn2OsI4NG4MvXpIPbrOYhi9Oe7SMPkn5fyYIeBZbw==
  template:
    metadata:
      name: ghcr-creds-hackathon-platform
      namespace: hackathon-platform
    type: kubernetes.io/dockerconfigjson
