apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hackathon-platform
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - hackathon.pseudolab-devfactory.com
      secretName: hackathon-platform-tls
  rules:
    - host: hackathon.pseudolab-devfactory.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: hackathon-platform-api
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hackathon-platform-web
                port:
                  number: 8080
