apiVersion: batch/v1
kind: Job
metadata:
  name: hackathon-platform-migrate
spec:
  template:
    spec:
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: migrate
          volumeMounts:
            - name: uploads
              mountPath: /data/hackathon-uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: hackathon-platform-uploads
