---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hackathon-platform-api-secret
  namespace: hackathon-platform
spec:
  encryptedData:
    DATABASE_URL: AgC/qKDE9tG6YjRaH7tpKtqllQtQUUWgvA+tpAuHrjCaxczn1o3D6NO2TRKvLWzMIcM2m2xTsiBQ9cUOvKx06B26+Nk9sWCuBxTUvUfagdCyXhlBBzhoqRFm6B3GWVel9x2xPhg50CKALVoc2nrfEuBrOtOOLBjvVHgq6pX1NpEszfnYoZr0PGuuSEksnBI/VZycVqtAXnAPXDtpdfFLmNKa1qwHcBDgrMVxis9bZhXudYOzPpy5knNdgq0N9jRVDXeHRsnGVmyk5MIBjsdOV6Rz3YGVQzIWQ1rQB8ovwdVFf+28LX2nJOwD2j7ayz9RCBEoLXX7/awDFDzmObrrnj3yAIYg1ADKzxljPz4uKqdtxA/IPT39yZndy8r7u3nQEMBm5evZSycF/bViBUbF7rtohIx7fvW18TQJdy+lowRyoAIhf7Pyy2TNKXDybI1uiID+XL0zkak2ot43K98K18wkZ12nCFwYbD3B4PTarruAPOixFUElcHp254Vqq1/qGU1btqSmAxoqKYXtt3w4xvnF9vGNH7DZ3iHi1BvrUHZ5Cj8KOcSr+oWwrGa0IOslu2ayicOLz7jjfoqDASix8cUKK3lGzjALF8BdIjqeFefCqyzhy6aXFXSLDorBoKR0HSBSew5IU2IYcQHDYSN+vA4VHml7fkbGBH3doPdgRz03UuwQ4yOgAKSNXxITA60IQf2Q1kxu5QhveyBqOV295TxjeiG+OUMclRnhRlCvaz3FxqM9siIXVMnMHL5RJA1JYGQB0N0ZPpFlqZ6zUnbOaUBZRU49hfU1PqqNl9F8yRpsK12jrv8rvdKtdlzCnWFFQ3uQs0DlxjyPTve03CQZaoWyyL8RF6t9Rc5q66otMJV6
  template:
    metadata:
      name: hackathon-platform-api-secret
      namespace: hackathon-platform
