apiVersion: v1
kind: PersistentVolume
metadata:
  name: hackathon-platform-uploads
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /var/lib/hackathon-platform/uploads
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - soo-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hackathon-platform-uploads
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: hackathon-platform-uploads
  resources:
    requests:
      storage: 50Gi
