apiVersion: apps/v1
kind: Deployment
metadata:
  name: experiment-platform-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: experiment-platform
      component: frontend
  template:
    metadata:
      labels:
        app: experiment-platform
        component: frontend
    spec:
      imagePullSecrets:
        - name: ghcr-creds-experiment-platform
      containers:
        - name: frontend
          image: ghcr.io/pseudo-lab/experiment-platform-pseudolab-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
