---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-creds
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAcrZeZt531ArzSxnb3rqiH3jLdjWuNhaToXjFE/G2CFVvNu0gVb4kZE60xguEyrXm30pcSJbTsd5JleC/VMe21u2v3ZKZvzH82b0xrYEq7Lt27fPf73Gw/umQo0JsKByyXTWB0rFO7eNp2gs7FTMjk0AzNf7zVwdiG8Xgori9NiyxabFLxNKOZvFgy7euvNZJnZ4CsQmzPbG6BicVWDMMkMuPg+zrIOw9K8cHj8nhGW6PfzKqOB04I8bEo1XK1om/sXWtU2cENI+kP+oz2BV2KRp0+76Kxq7JG93xkBD1/0+dNfP35htLlKTzFW26qxYWIL0ckt3boqdVQmpCb4IgXAEr2izInzziULmi0IzSHBIeCTrrZaXrbvGLnmKW5IuCIbuvki2uKCyo3zbhDmYPrQjoj+Uo+SPBAQerzsSYkbR8KHGE63pRu2gzJHwxtgTa1D+TjCuciL4ml0iL/S283pWg/WFDWFelX1RqnO9HVUOaxOQ3ECAT1Y50OZ//f4C5RvMqR1Qy46rIq+Qk0La/PgmT9B3dG9GUWF6psNQASz6teIddoytUTIQNYWvZxq72b4HPEksgMPfuH9seJy7kICOcHTUnsY5P7kYdvyCBItzH1F3nf0f6WEccyv+BDkvWetEGz+wuZCyQKftKTZ9gSaVbvuNBs7L0BnWzg7t03eIlsDMJdQpau0mX/y14uQyFnJUis8EKt+e+PBEA=
    admin-user: AgCF+0CXecnygzL3iUJ1xqUe7HcH6SlJUX6eNUAALWLI4hRDgYVu2e9z/iputOX+Ihbifr3M6bumXWKn3wpTsu0WL/KykoWEueGX5jNqCbbNrZ8/l8ZsVMcRQKSKBBb7k8J3av1dggzcjnCH5j3pdpfLl0bb7jzUIfZs/Nvz9y996EU/iF/hBR5q9ND/oMyj3jikHs1HBsf3KXu1lkIzlPdaqasnOnzt/QJ/3w3a4FL0+AiLNMdY6miUnV24ZHYlsHgAzeRSQjJQz81Oc09wNVgVCKHrhnE7q/hamBSb58wJcFDjhKODhhLkIh4R258K1qdbXS8dflDZS5WG6K1npfnZ9qvSxscODiTzWGm+21Lqx2bJDOtIDHsgRIKdlVoiX5a/4EAu88O5U/I9WsJahONCEo9dITWC8217r+qDiuBFnXPsrBgl2Ci9kJNEP1zRiWdsYIE0XZw/jYTYrQ2pGeaiTg5ADJIGQiaeBGEwgCwHkTQLZII7InfakV0W5oBgW1xN8l78WF00DCuEruzE+eWp5Y+S9Rc1EvaJHKh77kDhUVNABqIfnfvcRzzIAxLQoBE8NutqfGbolPgCMRcUkwwA5IViw1HKMszKlVMfU35ThAyqiDsIv3eWwUlrK+QSiiLj4CjMSmlZyMX0aBhWAhfqYqcF9AyDfCLLgap16CmDhFzxisXDxuSRsTmh1JEDMG1dxtxJIw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-creds
      namespace: monitoring
    type: Opaque
