apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-bingo-creds
  namespace: monitoring
spec:
  encryptedData:
    password: AgDHKTSGY/LXxqx5aJfazEhYYPjseC+S04Bte0bminYK9o83PP0vhGsQPxvSUZ/H8hv7wjgl+D9miLI/Tgv79BhWpqL5HWmHEYo6pQGYa0kHBa3EbeB2pTuNRRTG8hvtawW7bpEDKFeoY7tDnGfJBjB5edRfhhTuqZ58bdmQY1pSuXJ6kj+yBubIen771P2to6rt/3klkJFSItkcObQ5XHlzS1WqVTWLR4ixUx4U1ZeKkxX0WVEWVw56x06fjm9be6Ac9nLwLwntEu3LM1fRfWY14uqmnMguL9RNIIxYt12U43G/YjP4/2+hxEfWHAPr0Wa8JeAaBSUZadUEv5/0awpAMlWc8ZP1e93dftfaatXNBKBMKc7ap1mtyU3s1PnTvkVVs+Qelas41RBDipfw4i73+/+/BWa5awRnsviZgt6vCPYErzoHOzBYVn7+VfakYH7zQitUkhCfI+vRmy1+n3yfRVTSbkijq6cey3MCtZr3c99ccWrSclea3wFfmFLfSUVTX1GgPszxfP4+mrEIzqSpUrdm2B9RDkgMGG2CdpgAGK+H5WWDcej2McmN4cya10vpSxf6MpAUFD+7VXmFiu3yA5mDuTnGb78us4SRduqIxwt84TI6rBAkYMF37/2a1KN03XDnOarvE4oRvnJ2oU5j5WvV3npinkZSTF+d3flLRWNo8wFJYBkWipyOuvK8geh5c+lRN80/bqqFPUA=
    user: AgC68ZzuDeKoE0lu5LogyKAHNbexB/m1VnCcgqOIqZEtuqGazGH9pwNnq/YBC9VV4Pqo9FjrZmQNgBXA5PXFRxuspSsjboz+zHbFlIr3ZJ7HR/Ue843/deqGux0v35EptRONaJrO7Rr04X/DBk+MOQX2iiDto9b6s6K7l0NNS7QlLYSI1nvbEcsQvRDOA4V1/CQmgIiecjImGybWDrWGTHETS8QdOMA1MgfG2a0jE8fpeBFpN8BQyiI293KWIy1sSyATdoFhQW/gWs+o0vHTC4arI/8E7SpdSk1fArJXYZDfVkwLW0+8FBoL6g8UGYsz1WdSbQh16sX2L8bNljQzhxD24BhVZP4sMGgboIASI7t3qLV7EcGr/t/jqbuC858LmvoqgwcZGysSZghnb3wlz10ZF36hX5yI1Yac/DmdmaSuJ8H1g2C459CZPXf5WscUPEZt1QQ9phH34KfaOkpqKW5jf5aJw55B6Y0peSEHkE5cUGNDjnd+cVqo+F1nMW5dLDOJju3fxeLvoON2h4Q+n0HvBDZ2Htfdm1tHqnk8Ox5lpKNaMvDBCE5BraOcxpb1y7rUEjr4WAd2WKj6t+e0pEnfksSBSDzvwU99sCDHDpQbJI0N0uxJCkaASGFoIc8H24VCc8uWbT9rRpa8q0njMmPvb2X1nWVZXYpHzbPK+5YqJWeViYxIKan7ZpXCCY1TUnurOx/pthKnE5I=
  template:
    metadata:
      name: grafana-bingo-creds
      namespace: monitoring
    type: Opaque
